image: gitpod/workspace-python

ports:
  - port: 5000
    onOpen: open-preview
    description: University of Savoy - Flask Sample app

tasks:
  - init: |
      pip install -r requirements.txt
      flask init-db
  - command: |
      flask run

vscode:
  extensions:
    - ms-python.python
